# Generated by Django 5.2.7 on 2025-11-02 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Lembrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_hora', models.DateTimeField()),
                ('enviado', models.BooleanField(default=False)),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lembretes', to='contatos.contato')),
            ],
        ),
    ]
